name: Auto Contribution

on:
  schedule:
    - cron: "0 */6 * * *" # Runs every 6 hours

jobs:
  run_report:
    runs-on: ubuntu-latest # Use the latest Ubuntu image for the runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Run the script to generate the report
      - name: Run script to generate report
        run: |
          python scripts/generate_report.py
          echo "Report generated successfully!"  # Optional: Success message after script execution

      # Step 3: Commit and push the changes to the repository
      - name: Commit and push changes
        run: |
          git config --global user.email "shubhmaheshwari8193@gmail.com"  # Your GitHub email
          git config --global user.name "shubhmaheshwari27"  # Your GitHub username
          git add reports/report.txt  # Add the modified report file to the commit
          git commit -m "Update report with new data"  # Commit the changes
          git push origin master  # Push changes to the master branch (or use your relevant branch)
